### PR TITLE
fix: Build query object from text search

### PR DESCRIPTION
**Pull request by mcschwartzman**
@rgov Thoughts on this? Not sure how fast this is going to be on the prod db, but afaict there's no way to test that without pushing.

cc @ahimahis

### CODE REVIEW

**Comment by rgov** [comment]
What is the `fulltext` field?

I think searching by regular expression is interesting but it is likely to be far, far slower than just text search. And it might confuse users; typing an invalid regular expression for instance would likely error rather than return a match.

**Comment by mcschwartzman** [comment]
The `RegExp(request.query.fulltext, 'i')` object is just a case-insensitive search. I don't expect users to search by regex, this is just backend support to essentially combine the "event_value" and "event_free_text" search (and also search in the "event_option_values")

**Comment by mcschwartzman** [comment]
fake-full-text-search

**Comment by rgov** [comment]
Oh I see what you're doing, it's more like a new feature than a fix? You'd still want to take the user's input and escape it (like with [this NPM package](https://www.npmjs.com/package/escape-string-regexp) or [lodash](https://lodash.com/docs#escapeRegExp) or [something else reasonable from here](https://stackoverflow.com/questions/3446170/escape-string-for-use-in-javascript-regex/6969486#6969486)) so it doesn't get interpreted as a regular expression.

I still think it would likely be pretty slow. But I see that the existing code is also doing regex-based search. With this negation search with `!` etc... I would just rip that stuff out. It's not great.

Then full text search could be the *only* text search option. And the code would be a lot simpler.

**Comment by mcschwartzman** [comment]
The regex exclusive event_value search is a little more baked into how we display ASNAPs so it might be worth revisiting that in a future issue after we option some more db changes.

**Review by rgov — CHANGES_REQUESTED** [review]
Thanks.

You'll need to add `package.json` after adding the new `escape-string-regexp` package so that it gets included in the Docker container.

**Pull request merged**
